[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "usart"
version = "0.1.0"

[dependencies]
aux11 = { path = "auxiliary" }

[dependencies.heapless]
default-features = false
version = "0.3.7"
